config/routes.rb
Rails.application.routes.draw do

  get "/rooms/:user_id", :to=>"rooms#show",param: :username,as: :room

  resources :ikebanas
  resources :shousetukansous
  devise_for :admin_users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'


  resources :comments

  resources :news

  resource :votes

  root 'home#index'



  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    :registrations => 'users/registrations' }


   resources :users do
     resources :user_abouts ,:only => [:index,:create,:update,:show]
   end

  resources :novels ,:as => :novels

  get '/novels/short_short_story', to: 'novels#short_short_story', as: :short_short_story

  get '/ssses/shousetukansous', to: 'ssses#shousetukansous', as: :ssses_shousetukansous

  get '/ssses/user_about', to: 'ssses#user_about', as: :ssses_user_about

  post '/ssses/user_about', to: 'ssses#create_user_about'
  patch '/ssses/user_about', to: 'ssses#update_user_about'
  put '/ssses/user_about', to: 'ssses#update_user_about'

  # ここはsssesのコメント部

  post '/ssses/comment', to: 'ssses#comment_create'


# コメントを編集したいが、黒い画面に飛ぶ　まだ未実装
  patch '/ssses/comment', to: 'ssses#comment_update'
  put '/ssses/comment', to: 'ssses#comment_update'

  # ここはsssesのお知らせedit お試し中
  post '/ssses/news', to: 'ssses#create_news'
  patch '/ssses/news', to: 'ssses#update_news'
  put '/ssses/news', to: 'ssses#update_news'

  get '/ssses/ichiran', to: 'ssses#ichiran' ,as: :ssses_ichiran

  get '/ssses/chokkin_novels_zenran', to: 'ssses#chokkin_novels_zenran' ,as: :ssses_chokkin_novels_zenran

  # うるまさん居ない時に　4/12

  get '/ssses/show_user_about_novel', to: 'ssses#show_user_about_novel',as: :ssses_user_about_novel

  # get '/ssses/shousetukansous/:shousetukansou_id' => 'ssses#show_shousetukansou',path: "ssses/shousetukansous/:shousetukansou_id" ,as: :ssses_shousetukansou
  # get '/ssses/shousetukansous/new' => 'ssses#new_shousetukansou',path: "ssses/shousetukansous/new" ,as: :new_ssses_shousetukansou
  # get '/ssses/shousetukansous/:shousetukansou_id/edit' => 'ssses#edit_shousetukansou',path: "ssses/shousetukansous/:shousetukansou_id/edit" ,as: :edit_ssses_shousetukansou
  # post '/ssses/shousetukansous' => 'ssses#create_shousetukansou',path: "ssses/shousetukansous/" ,as: :ssses_shousetukansous
  # patch '/ssses/shousetukansous/:shousetukansou_id' => 'ssses#update_shousetukansou',path: "ssses/shousetukansou/" ,as: :ssses_shousetukansou
  # put '/ssses/shousetukansous/:shousetukansou_id' => 'ssses#update_shousetukansou',path: "ssses/shousetukansou/" ,as: :ssses_shousetukansou


# うるまさんがいない時に9/10

  get '/ssses/message_ichiran', to: 'ssses#message_ichiran', as: :ssses_message_ichiran

  resources :ssses ,:as => :ssses


  resources :shougis

  get 'about', to: 'home#about', as: :about
  get 'tukaikata', to: 'home#tukaikata',as: :tukaikata

  mount ActionCable.server => '/cable'

  get '/ssses/vote/result', to: 'votes#result' ,as: :ssses_votes_result

end

app/controllers/ssses_controller.rb
class SssesController < ApplicationController

  before_action :set_novel, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user! , only:[:new,:create,:edit,:update,:destroy,:create_user_about,:update_user_about,:comment_create,:comment_update]
  before_action :nanasi_user_about! , only:[:new,:create,:edit,:update,:destroy]
  before_action :tanin_ijiri!, only:[:edit,:update,:destroy]

  before_action :check_notice,only:[:show]
  before_action :get_notices

  before_action :get_message_notice
  before_action :get_deadline
  layout 'short_short_story' #これで、ショートとのレイアウトが呼び込まれる
  # GET /novels
  # GET /novels.json

  def index

    @users = []
    @comments = []

    @now_news = News.ssses.new_news.order_d
    @old_news = News.ssses.old_news.order_d
    puts  "--------------#{@now_news.inspect}-----------"
    puts  "--------------#{@old_news.inspect}-----------"

    @params = "ssses"

  # うるまさんがいない時に11/19
  # if @today < @happyou
  #   @novels = Novel.where(flag:true,label:"sss",genre:Novel.genre_list_ssses_1).or(Novel.where(flag:true,label:"sss",genre:Novel.genre_list_ssses_ivent_maturinasi_toukou)).order(toukouhiduke: :DESC)
  # else
    @novels = Novel.includes(user: :user_about).where(flag:true,label:"sss",genre:Novel.genre_list_ssses_1).or(Novel.includes(user: :user_about).where(flag:true,label:"sss",genre:Novel.genre_list_ssses_ivent_toukou)).order(toukouhiduke: :DESC)
  # end

    @chokkin_novels = @novels.first(5)


    @kaigi =Novel.includes(user: :user_about).where(flag:true,label:"sss",genre:"会議",past_work:false).order(toukouhiduke: :DESC).first(5)
    @zatudan =Novel.includes(user: :user_about).where(flag:true,label:"sss",genre:"雑談",past_work:false).order(toukouhiduke: :DESC).first(5)


    @sinsaku_nichijou_novels =Novel.includes(user: :user_about).where(flag:true,label:"sss",genre:"日常",past_work:false).order(toukouhiduke: :DESC).first(5)
    @past_work_nichijou_novels =Novel.includes(user: :user_about).where(flag:true,label:"sss",genre:"日常",past_work:true).order(toukouhiduke: :DESC).first(10)

    @sinsaku_renai_novels =Novel.includes(user: :user_about).where(flag:true,label:"sss",genre:"恋愛",past_work:false).order(toukouhiduke: :DESC).first(5)
    @past_work_renai_novels =Novel.includes(user: :user_about).where(flag:true,label:"sss",genre:"恋愛",past_work:true).order(toukouhiduke: :DESC).first(10)

    @sinsaku_joke_novels =Novel.includes(user: :user_about).where(flag:true,label:"sss",genre:"ジョーク",past_work:false).order(toukouhiduke: :DESC).first(5)
    @past_work_joke_novels =Novel.includes(user: :user_about).where(flag:true,label:"sss",genre:"ジョーク",past_work:true).order(toukouhiduke: :DESC).first(10)

    @sinsaku_siriz_novels =Novel.includes(user: :user_about).where(flag:true,label:"sss",genre:"シリーズ",past_work:false).order(toukouhiduke: :DESC).first(5)
    @past_work_siriz_novels =Novel.includes(user: :user_about).where(flag:true,label:"sss",genre:"シリーズ",past_work:true).order(toukouhiduke: :DESC).first(10)

    @sinsaku_doutitle_novels =Novel.includes(user: :user_about).where(flag:true,label:"sss",genre:"同タイトル",past_work:false).order(toukouhiduke: :DESC).first(5)
    @past_work_doutitle_novels =Novel.includes(user: :user_about).where(flag:true,label:"sss",genre:"同タイトル",past_work:true).order(toukouhiduke: :DESC).first(10)

    @sinsaku_sandaibanasi_novels =Novel.includes(user: :user_about).where(flag:true,label:"sss",genre:"三題噺",past_work:false).order(toukouhiduke: :DESC).first(5)
    @tukurikake_novels=Novel.includes(user: :user_about).where(flag:true,label:"sss",genre:"作りかけ作品を完成に！",past_work:false).order(toukouhiduke: :DESC).first(5)
    @sinsaku_maturi_novels =Novel.includes(user: :user_about).where(flag:true,label:"sss",genre:"祭り",past_work:false).order(toukouhiduke: :DESC).first(5)

    @kotoshino_maturi_novels =Novel.includes(user: :user_about).where(flag:true,label:"sss",genre:"祭り",past_work:false,toukouhiduke:@deadline.prev_month(4)..@deadline.next_month(4)).order(toukouhiduke: :DESC)

    @nabetani_novels = Novel.includes(user: :user_about).where(flag:true,label:"sss",genre:"鍋谷さんの娘さん",past_work:false).order(toukouhiduke: :DESC).first(5)

    @ivent =Novel.includes(user: :user_about).where(flag:true,label:"sss",genre:"イベント開催",past_work:false).order(toukouhiduke: :DESC).first(5)
    @ivents =Novel.includes(user: :user_about).where(flag:true,label:"sss",genre:"イベント開催",past_work:false).order(toukouhiduke: :DESC)

    @kikaku =Novel.includes(user: :user_about).where(flag:true,label:"sss",genre:"イベント企画",past_work:false).order(toukouhiduke: :DESC).first(5)
    @offkai =Novel.includes(user: :user_about).where(flag:true,label:"sss",genre:"オフ会",past_work:false).order(toukouhiduke: :DESC).first(5)

    # 無限スクルールの変数
    @aisatu =Novel.includes(user: :user_about).where(flag:true,label:"sss",genre:"挨拶",past_work:false).includes(:comments).order(toukouhiduke: :DESC).page(params[:page]).per(5)
    @aisatu_comments=[]
    @aisatu.each do |aisatu|
      if aisatu.comments.present?
        aisatu.comments.each do |comment|

          if comment.created_at.year == Date.today.year && (comment.created_at.month == Date.today.last_month.month || comment.created_at.month == Date.today.month)
            @aisatu_comments.unshift(comment)
          end
        end
      end
    end
    @sinsaku_nichijou_novels =Novel.includes(user: :user_about).where(flag:true,label:"sss",genre:"日常",past_work:false).order(toukouhiduke: :DESC).first(5)
    @past_work_nichijou_novels =Novel.includes(user: :user_about).where(flag:true,label:"sss",genre:"日常",past_work:true).order(toukouhiduke: :DESC).first(5)
    @joke_users=[]
    @joke_novels =Novel.includes(user: :user_about).where(flag:true,label:"sss",genre:"ジョーク").order(past_work: :ASC,toukouhiduke: :DESC).first(2)
    @joke_novels
    i=0
    @joke_novels.each do |novel|
      @joke_users[i]=User.find(novel.user_id)
      i=i+1
    end
    @siriz_users=[]
    @siriz_novels =Novel.includes(user: :user_about).where(flag:true,label:"sss",genre:"シリーズ").order(past_work: :ASC,toukouhiduke: :DESC).first(2)
    i=0
    @siriz_novels.each do |novel|
      @siriz_users[i]=User.find(novel.user_id)
      i=i+1
    end
    @doutaitle_users=[]
    @doutaitle_novels =Novel.includes(user: :user_about).where(flag:true,label:"sss",genre:"同タイトル").order(past_work: :ASC,toukouhiduke: :DESC).first(3)
    i=0
    @doutaitle_novels.each do |novel|
      @doutaitle_users[i]=User.find(novel.user_id)
      # @comments[i] = Comment.where(novel_id:novel.id)
      i=i+1
    end
    @shozokus = Shozoku.where(name:"超短編小説会").order(created_at: :ASC)

    # @votes = Vote.where

    # 投票者をとってきた
     voter_ids = Vote.where('created_at > ?',Date.new(@today.year,1,11)).pluck(:voter_id).uniq
     puts "--------------#{voter_ids.inspect}-----------"
     @ranking = {}

     voter_ids.each do |id|
       count =0
       votes = Vote.where('created_at > ?',Date.new(@today.year,1,11)).where(voter_id:id)
       votes.each do |vote|
         novel = Novel.find(vote.novel_id)
         if novel.user_id == vote.writer_id
           count += 1
         end
       end
       @ranking[id] = count
     end

     @ranking = @ranking.sort_by{ |_, v| -v }.to_h
     if @ranking.present?
       MaturiateShougou.create_shougou(User.find(@ranking.to_a.last[0]))
       logger.debug"-------------#{@ranking.to_a.last[0]}--------------------"
     end
  end

  def ichiran

    @sinsaku_novels = Novel.includes(user: :user_about).where(flag:true,label:"sss",genre:params[:genre],past_work:false).order(toukouhiduke: :DESC)
    @past_work_novels = Novel.includes(user: :user_about).where(flag:true,label:"sss",genre:params[:genre],past_work:true).order(toukouhiduke: :DESC)

    # @users = []
    # i=0
    # @novels.each do |novel|
    # @users[i]=User.find(novel.user_id)
    # i=i+1
    # end

  end

  def chokkin_novels_zenran
      # うるまさんがいない時に11/19
    # if @today < @happyou
    #   @novels = Novel.where(flag:true,label:"sss",genre:Novel.genre_list_ssses_1).or(Novel.where(flag:true,label:"sss",genre:Novel.genre_list_ssses_ivent_maturinasi_toukou)).order(toukouhiduke: :DESC)
    # else
      @chokkin_novels = Novel.includes(user: :user_about).where(flag:true,label:"sss",genre:Novel.genre_list_ssses_1).or(Novel.includes(user: :user_about).where(flag:true,label:"sss",genre:Novel.genre_list_ssses_ivent_toukou)).order(toukouhiduke: :DESC).page(params[:page]).per(10)
    # end

  end


  # GET /novels/1
  # GET /novels/1.json
  def show

    if @novel.flag
      @user = User.find(@novel.user_id)
      @user_about=UserAbout.find_by(user_id:@user.id)
      @comments = @novel.comments.order(created_at: :ASC)
      if params[:comment_id].present?
        @comment = Comment.find(params[:comment_id])
      else
        @comment  = @novel.comments.build(user_id: current_user.id) if current_user
      end
    else
      redirect_to ssses_path
    end
  end

  # GET /novels/new
  def new
    @novel = Novel.new
    #  if params[:preview_button] || !@novel.save
    #  @user = User.find(current_user.id)
    #  @comment = nil
    #  @user_about = UserAbout.find_by(user_id:@user.id)
    #  end
  end

  # GET /novels/1/edit
  def edit
  end

  # POST /novels
  # POST /novels.json
  def create
    @novel = Novel.new(sss_params)


    if params[:preview_button]
      @user = User.find(current_user.id)
      @user_about = UserAbout.find_by(user_id:@user.id)
      @comment = nil
      render :new and return
    end

    if params[:sitagaki]
      @novel.flag = false
    else
      @novel.flag = true
      @novel.toukouhiduke = DateTime.now()
    end

    @novel.label = "sss"

    respond_to do |format|
      if @novel.save

        if @novel.flag == false
          format.html { redirect_to ssses_user_about_path+"?user_id=+#{@current_user.user_about.user_id}", notice: '下書き保存しました！' }
        elsif Novel.genre_list_ssses_ivent.include?(@novel.genre)
          format.html { redirect_to ssses_path ,notice: "イベントのトピックを作成しました！　おつかれさまです。" }

app/helpers/ssses_helper.rb
module SssesHelper
  def set_class(genre)
   if genre == "日常"
     return "sample-box-nichijou"
   elsif genre == "恋愛"
     return "sample-box-renai"
   elsif genre == "ジョーク"
     return "sample-box-joke"
   elsif genre == "同タイトル"
     return "sample-box-doutai"
   elsif genre == "シリーズ"
     return "sample-box-siri"
   end
  end

 def read_flag_check(read_flag)
  if !read_flag
    return "<span class='non_read'>●</span>"
  end
 end

 # def user_name(user_id)
 #   UserAbout.find_by(user_id:user_id).name
 # end


end

app/views/ssses/_aisatu_mugen.html.erb
<div class="aisatu_mugen">
<% @aisatu.each do |aisatu| %>
<ul>
  <li style="  list-style:none;">

    <%= render 'ssses/user_gazou', {user:aisatu.user,user_about:aisatu.user.user_about} %>

    <%= link_to user_name(aisatu.user).html_safe,ssses_user_about_path(user_id:aisatu.user.user_about.user_id) %>:

    <br/>
    「<%= aisatu.honbun %>」
  </li>
</ul>
<% end %>
</div>

<% page = session[:page]+1 %>
<% session[:page] += 1 %>
<%#= path_to_next_page @aisatu %>
<%= link_to_next_page @aisatu, 'もっと見る', id: "page#{page}",class:'read_more', remote: true %>

app/views/ssses/_novels.html.erb
<div class="container">
<table class="table table-striped table-hover hidari-yohaku5">
  <thead>
    <tr>
      <th>
       ジャンル
      </th>
      <th>
       タイトル
      </th>

      <% if tukurikake == false %>
      <th>
      コメ
     </th>
     <% end %>

      <% if tukurikake == false %>
     <th>
       投稿日時
     </th>
     <% else %>
     <th>
       作成日時
     </th>
     <% end %>

     <th>
       修正日時
     </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

<% i=0 %>
    <% novels.each do |novel| %>
    <tr>
      <td>
       <%= novel.genre %>
      </td>
        <td>
         <%= novel.title.truncate(20) %>
        </td>


        <% if tukurikake == false %>
        <td>
        <%= link_to comments[i].count,novel %>
       </td>
       <% end %>

        <td>
         <%= novel.created_at.to_s(:compact_day)  %>
        </td>
        <td>
<% i +=1 %>
           <% if novel.created_at == novel.updated_at %>
            −
           <% else %>
           <%= novel.updated_at.to_s(:compact_day)  %>
           <% end %>
        </td>



        <td class="btn btn-success">
        <% if Novel.genre_list_ssses_foram.include?(novel.genre) %>
        <%= link_to '仕上げる', edit_sss_path(novel,flag:true) %>
        <% elsif Novel.genre_list_ssses_ivent.include?(novel.genre) %>
        <%= link_to '仕上げる', edit_sss_path(novel,ivent_flag:true) %>
        <% elsif Novel.genre_list_ssses_ivent_toukou.include?(novel.genre) %>
        <%= link_to '仕上げる', edit_sss_path(novel,ivent_toukou_flag:true) %>
        <% else %>
        <%= link_to '仕上げる', edit_sss_path(novel) %>
        <% end %>
       </td>

        <td class="novel btn btn-danger">  <%= link_to '削除', sss_path(novel), method: :delete, data: { confirm: '削除してもよろしいでしょうか?' },style:"color:black;" %></td>
                                <!-- user_about?user_id=+8 -->
<!-- <%#= ssses_user_about_url %>?user_id=<%#=novel.user_id%> -->


      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate novels %>
</div>

app/views/ssses/_show_nakami.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <% if controller.action_name == "show" %>
  <ul class ="pager">
    <li>  <%= link_to '一覧に戻る', ssses_path %></li>
    &nbsp; &nbsp; &nbsp;
    <li>  <%= link_to "←前", sss_path(@novel.previous) if @novel.previous %></li>
    &nbsp; &nbsp; &nbsp;
    <li> <%= link_to '後→', sss_path(@novel.next) if @novel.next %></li>
  </ul>
  <% end %>



  <div class="text-center opacity">

    <% if browser.device.mobile? %>
    <h1 style="text-align:left">

      <%= @novel.title %>

    </h1>
    <%else %>
    <h1>

      <%= @novel.title %>

    </h1>
    <% end %>

    <!-- <%#= @novel.genre2_list.each do |tag| %>
    <p><%#= tag %></p>
    <%# end %> -->

  </div>
  <div class="text-left opacity">
    <li>
      <span id="txtnum"><%= mojibetu @novel.honbun %></span>
    </li>
    <li>
      <%= @novel.genre %>
    </li>

    <% if controller.action_name == "show" %>
    <li>
      <%= @novel.toukouhiduke.to_s(:compact_day)%>
    </li>
    <% end %>

    <br/>
    <li class="author">
      <% if @user.blank? %>
       著者：<a href="<%= ssses_user_about_url %>?user_id=<%=@novel.user_id%>"><%= user_name(current_user).html_safe %></a>
      <% elsif @user.deleted == true %>
      著者：<a href="<%= ssses_user_about_url %>?user_id=<%=@novel.user_id%>">退会済み</a>
      <% elsif  @user.deleted == false %>

        <% if @novel.genre == "祭り" && @today < @happyou %>
        著者：ないしょだよ
        <% else %>
        著者：<a href="<%= ssses_user_about_url %>?user_id=<%=@novel.user_id%>"><%= user_name(@novel.user).html_safe %></a>
        <% end %>

      <% end %>
    </li>

  </div>

  <div class="line space-choi novel-line"></div>

<%# if @novel.user_id == 10 %>
  <%#= simple_format(@novel.honbun, class: 'honbun') %>
<%# else %>
  <p class="honbun" style="word-wrap:break-word; overflow: auto;">
    <%= br(@novel.honbun) %>
  </p>
<%# end %>

  <% if @novel.genre == "祭り" && @today < @happyou  %>
  <div style = "float:right">【投稿者：ないしょだよ】</div>
  <% else %>
  <div style = "float:right">【投稿者：<%= user_name(@novel.user).html_safe %>】</div>

  <% end %>
  <br/>

  <% if @novel.atogaki.present? %>
  <div class="line" style="margin-top:20px;">
  </div>
  <div style="margin-top:20px;">
    <P class="honbun" style="font-weight:bold;">あとがき</p>
      <p class="honbun" style="word-wrap:break-word; overflow: auto;margin-bottom:20px;">
        <%= br(@novel.atogaki) %>
      </p>
    </div>
    <div class="line novel-line" style="margin-bottom:20px">
    </div>
    <% end %>



    <!--　うるまさんいない時にツイート機能を追加  -->
 <% if @novel.genre != "祭り" || @today > @happyou %>
    <% if controller.action_name == "show" %>
      <% if user_signed_in? && @novel.user_id != current_user.id %>
      <%= link_to "メッセージを送る",room_path(@user.id,label:"ssses"),class:"btn btn-xs btn-warning", :onclick=>"window.open(this.href,'hoge', 'height=800, width=800');return false;" %>
      <br/>
      <br/>
      <% end %>

      <% if user_signed_in? && @novel.user_id == current_user.id %>
      <a href="https://twitter.com/share" class="twitter-share-button" data-text="小説「<%= @novel.title %>」を書きました。" data-hashtags="超短編小説会,超短編小説,短編小説,掌編小説,小説">Tweet</a><span>・・・ツイッターに「書きました。」をする。</span> <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
      <% else %>
      <a href="https://twitter.com/share" class="twitter-share-button" data-text="<%= user_name(@novel.user).html_safe %>さんの小説「<%= @novel.title %>」を読みました。" data-hashtags="超短編小説会,超短編小説,短編小説,掌編小説,小説">Tweet</a><span>・・・ツイッターに「読みました。」をする。</span> <script>!function(d,s,id){var  js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
      <% end %>
    <% end %>
  <% end %>

    <br/>
    <% if controller.action_name == "show" || controller.action_name == "comment_create"  %>

    <% if user_signed_in? %>
    <% if @novel.user_id == current_user.id %>

    <div class="btn btn-success btn-success2">
      <% if Novel.genre_list_ssses_foram.include?(@novel.genre) %>
      <%= link_to '編集', edit_sss_path(@novel,flag:true) %>
      <% elsif Novel.genre_list_ssses_ivent.include?(@novel.genre) %>
      <%= link_to '編集', edit_sss_path(@novel,ivent_flag:true) %>
      <% elsif Novel.genre_list_ssses_ivent_toukou.include?(@novel.genre) %>
      <%= link_to '編集', edit_sss_path(@novel,ivent_toukou_flag:true) %>
      <% else %>
      <%= link_to '編集', edit_sss_path(@novel) %>
      <% end %>
    </div>

    <div class="novel btn btn-danger">
      <%= link_to '削除', sss_path(@novel) , method: :delete, data: { confirm: '削除してもよろしいでしょうか?' } %>
    </div>

    <% end %>
    <% end %>

    <!-- <div class="btn btn-info">
    <%#= link_to '一覧に戻る', ssses_path %>
  </div> -->

  <ul class ="pager">
    <li>  <%= link_to "←前", sss_path(@novel.previous) if @novel.previous %></li>
    &nbsp; &nbsp; &nbsp;
    <li> <%= link_to '後→', sss_path(@novel.next) if @novel.next %></li>
  </ul>

  <% if @comments.present? %>
  <p class="comment-ichiran"> コメント一覧　</p>
  <div class="space-choi line novel-line"></div>
  <% end %>

  <% i=1 %>
  <ol class="media-list">
    <% @comments.each do |comment| %>
    <!-- <div class="comment-kannren"> -->
    <li class="media">
      <span><%= i %>.</span>
      <% if comment.user.deleted == true %>
      <a class="media-left" href="<%= ssses_user_about_url %>?user_id=<%=comment.user_id%>"><%= image_tag("gaikotu.png",:size => "50x50") %></a>



      <div class="media-body">
        <h4 class="media-heading">
          <strong>
            <a href="<%= ssses_user_about_url %>?user_id=<%=comment.user_id%>">退会済み</a>

            <% else %>
            <% unless @novel.genre == "祭り" && @today < @happyou %>
              <a class="media-left" href="<%= ssses_user_about_url %>?user_id=<%=comment.user_id%>"><%#= ssses_profile_img(comment.user.user_about) %></a>
            <% end %>

           <div class="media-body">
              <h4 class="media-heading">
                <strong>
                  <% if @novel.genre == "祭り" && @today < @happyou %>
                    謎人
                  <% else %>
                  <a href="<%= ssses_user_about_url %>?user_id=<%=comment.user_id%>">
                    <%= user_name(comment.user).html_safe %>
                    <% end %>
                  </a>
                  <% end %>
                </strong>
              </h4>
                <p style="width:100%; display:table; table-layout:fixed; font-size:18px; word-wrap:break-word; overflow-wrap : break-word;overflow: auto;"><%= br(comment.body) %></p>
            </div>
            <br />
            <!-- コメント編集未実装  -->
            <% if user_signed_in? && comment.user == current_user %>
            <span><%= link_to 'コメント編集', sss_path(comment.novel_id,comment_id:comment.id),:class=>"btn btn-xs btn-info" %></span>
            <% end %>

            <% if user_signed_in? && comment.user == current_user %>
            <span><%= link_to 'コメント削除', comment_path(comment,docchi:"sss"), method: :delete,data: { confirm: '削除してもよろしいでしょうか?' },:class=>"btn btn-xs btn-danger" %></span>
            <% end %>
          </li>
          <!-- </div> -->
          <% i +=1 %>
          <% end %>
        </ol>



        <% if user_signed_in? %>
        <%= render 'ssses/comment_form' %>
        <% end %>


        <% end %>
      </div>
    </div>

app/views/ssses/comment_edit.html.erb
<div class="container">
<h1>こめんと編集</h1>

<%= render 'comment/form', comment: @comment %>

<%= link_to '見る', @comment %> |
<%= link_to '戻る', comments_path %>
</div>

app/views/ssses/new.html.erb
<% if params[:flag] %>
<h1>フォーラムのトピック作成中</h1>
<%elsif params[:ivent_flag] %>
<h1>イベントのトピック作成中</h1>
<% else %>
<h1>新規小説作成中</h1>
<% end %>
<%= render 'ssses/form', novel: @novel %>

<%= link_to '戻る', ssses_path %>

app/views/ssses/show.html.erb
<%= render 'show_nakami' %>