config/routes.rb
Rails.application.routes.draw do

  get "/rooms/:user_id", :to=>"rooms#show",param: :username,as: :room

  resources :ikebanas
  resources :shousetukansous
  devise_for :admin_users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'


  resources :comments

  resources :news

  resource :votes

  root 'home#index'



  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    :registrations => 'users/registrations' }


   resources :users do
     resources :user_abouts ,:only => [:index,:create,:update,:show]
   end

  resources :novels ,:as => :novels

  get '/novels/short_short_story', to: 'novels#short_short_story', as: :short_short_story

  get '/ssses/shousetukansous', to: 'ssses#shousetukansous', as: :ssses_shousetukansous

  get '/ssses/user_about', to: 'ssses#user_about', as: :ssses_user_about

  post '/ssses/user_about', to: 'ssses#create_user_about'
  patch '/ssses/user_about', to: 'ssses#update_user_about'
  put '/ssses/user_about', to: 'ssses#update_user_about'

  # ここはsssesのコメント部

  post '/ssses/comment', to: 'ssses#comment_create'


# コメントを編集したいが、黒い画面に飛ぶ　まだ未実装
  patch '/ssses/comment', to: 'ssses#comment_update'
  put '/ssses/comment', to: 'ssses#comment_update'

  # ここはsssesのお知らせedit お試し中
  post '/ssses/news', to: 'ssses#create_news'
  patch '/ssses/news', to: 'ssses#update_news'
  put '/ssses/news', to: 'ssses#update_news'

  get '/ssses/ichiran', to: 'ssses#ichiran' ,as: :ssses_ichiran

  get '/ssses/chokkin_novels_zenran', to: 'ssses#chokkin_novels_zenran' ,as: :ssses_chokkin_novels_zenran

  # うるまさん居ない時に　4/12

  get '/ssses/show_user_about_novel', to: 'ssses#show_user_about_novel',as: :ssses_user_about_novel

  # get '/ssses/shousetukansous/:shousetukansou_id' => 'ssses#show_shousetukansou',path: "ssses/shousetukansous/:shousetukansou_id" ,as: :ssses_shousetukansou
  # get '/ssses/shousetukansous/new' => 'ssses#new_shousetukansou',path: "ssses/shousetukansous/new" ,as: :new_ssses_shousetukansou
  # get '/ssses/shousetukansous/:shousetukansou_id/edit' => 'ssses#edit_shousetukansou',path: "ssses/shousetukansous/:shousetukansou_id/edit" ,as: :edit_ssses_shousetukansou
  # post '/ssses/shousetukansous' => 'ssses#create_shousetukansou',path: "ssses/shousetukansous/" ,as: :ssses_shousetukansous
  # patch '/ssses/shousetukansous/:shousetukansou_id' => 'ssses#update_shousetukansou',path: "ssses/shousetukansou/" ,as: :ssses_shousetukansou
  # put '/ssses/shousetukansous/:shousetukansou_id' => 'ssses#update_shousetukansou',path: "ssses/shousetukansou/" ,as: :ssses_shousetukansou


# うるまさんがいない時に9/10

  get '/ssses/message_ichiran', to: 'ssses#message_ichiran', as: :ssses_message_ichiran

  resources :ssses ,:as => :ssses


  resources :shougis

  get 'about', to: 'home#about', as: :about
  get 'tukaikata', to: 'home#tukaikata',as: :tukaikata

  mount ActionCable.server => '/cable'

  get '/ssses/vote/result', to: 'votes#result' ,as: :ssses_votes_result

end

app/views/battle/_comment_form.html.erb
<%= form_for @comment, url: ssses_comment_path do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <%= f.hidden_field :user_id %>
  <%= f.hidden_field :novel_id %>
  <%= hidden_field_tag :comment_id,@comment.id%>

  <% if controller.action_name == "show_user_about_novel"  %>
  <%= hidden_field_tag :flag,true %>
  <% end %>
  
  <div class="form-group">
  <%= f.label :body,"コメント"%><br/>
  <% if browser.device.mobile? %>
  <%= f.text_area :body ,:style =>"width:100%;height:400px",:id=>"count" %>
  <% else %>
  <%= f.text_area :body,:style =>"width:100%;height:400px",:id=>"count" %>
  <% end %>

    <div class="actions">
  <% if params[:comment_id].present? %>
  <%= f.submit "コメント編集する" %>
  <% else %>
  <%= f.submit "コメントする" %>
  <% end %>
  </div>

<% end %>

app/views/battle/_communication.html.erb
<div class="container">
<h2 style="margin-bottom:20px;"><strong  style="background: linear-gradient(transparent 60%, #ffff66 60%);" id="scroll_5">5.コミュニケーション</strong></h2>


<% if @aisatu_comments.present? %>
<div class="sample-box-12">
<!-- &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="background: linear-gradient(transparent 60%, #ffff66 60%);margin-bottom:35px;">☆先月と今月のご挨拶☆</span> -->
      <% if browser.device.mobile? %>
<h4 style="text-align: center;"><strong style="background: linear-gradient(transparent 60%, #ffff66 60%);">☆先月と今月のご挨拶☆</strong><h4>
  <% else %>
<h3 style="text-align: center;"><strong style="background: linear-gradient(transparent 60%, #ffff66 60%);">☆☆☆☆先月と今月のご挨拶☆☆☆☆</strong><h3>
<% end %>

 <% @aisatu_comments.each do |aisatu_come| %>
 <ul>
   <li style="  list-style:none;">
     <% if aisatu_come.user.user_about.image.present? %>
     <%= link_to image_tag(aisatu_come.user.user_about.image.to_s,ssses_user_about_path(user_id:aisatu_come.user.user_about.user_id) %>
     <% elsif aisatu_come.user.image_url.present? %>
     <%= link_to image_tag(aisatu_come.user.image.to_s,:size => '50x50'),ssses_user_about_path(user_id:aisatu_come.user.user_about.user_id) %>
     <% else %>
     <%= link_to image_tag("ikebana.png",:size=>'25x25'),ssses_user_about_path(user_id:aisatu_come.user.user_about.user_id) %>
     <% end %>
     <%= link_to user_name(aisatu_come.user).html_safe,ssses_user_about_path(user_id:aisatu_come.user.user_about.user_id) %>:
      <% if browser.device.mobile? %>
      <br/>
      <% end %>
     「<%= aisatu_come.body %>」
   </li>
 </ul>
 <% end %>
</div>
<% end %>



<h4><span style="background: linear-gradient(transparent 60%, #ffff66 60%)">(1)挨拶/会議/雑談</span></h4>


<!-- <ul class="nav nav-tabs">
<li class="active"><a href="#zatudan" data-toggle="tab" aria-expanded="true" style="font-size:18px">挨拶など</a></li>
</ul>

<div class="tab-pane fade" id="zatudan"> -->
  <% if user_signed_in? %>
   <%= link_to new_sss_path(flag:true) do %>
   <div style="margin:10px 10px 60px 10px;">
   <%= image_tag("foram.jpg",:size => "70x70",:class=>"hoverImg",style:"float:left") %>
   <p style="padding: 30px 0 0 80px;font-size: 18px;">新規にトピックスを作成</p>
  </div>
  <% end %>
  <% end %>
  <div>
  <%= render 'novels_ichiran_format',novels:@aisatu,genre_shurui:"挨拶" %>
  <%= render 'novels_ichiran_format',novels:@kaigi,genre_shurui:"会議" %>
  <%= render 'novels_ichiran_format',novels:@zatudan,genre_shurui:"雑談" %>
  </div>
<!-- </div> -->



<h4><span style="background: linear-gradient(transparent 60%, #ffff66 60%)">(2)チャット交流</span></h4>
<p>チャットルームは火曜日と土曜日の２０～２２時くらいに開催されることがあります。</p>
<div style="float:left;">
  <%= link_to "http://chat.kanichat.com/chat?roomid=ssstory_Room", :onclick=>"window.open(this.href,'hoge', 'height=800, width=800');return false;"  do %>
  <%= image_tag("illust3680.png",:size => "70x70",:class=>"hoverImg") %>
  <p style="text-align: center;"  >チャット</p>
</div>
  <% end %>

</div>

app/views/battle/_koukai_shousetu.html.erb
<div class="container">

<h2><strong style="background: linear-gradient(transparent 60%, #ffff66 60%);" id="scroll_2">2. 小説</strong></h2>

<!-- 小説電光 -->


    <div class="hidari-yohaku5" style="padding:5px;margin:10px 0 10px 0;">
      <ul class="nav nav-tabs">
        <li class="active"><a href="#home" data-toggle="tab" aria-expanded="true" style="font-size:18px">新作</a></li>
        <li><a href="#profile" data-toggle="tab" aria-expanded="true" style="font-size:18px">過去作</a></li>

      </ul>

      <div id="myTabContent" class="tab-content">

        <div class="tab-pane fade active in" id="home">
          <% if user_signed_in? %>
            <%= link_to new_sss_path(past_work_flag:false) do %>
             <div style="margin:10px 10px 60px 10px">
             <%= image_tag("pen.jpg",:size => "70x70",:class=>"hoverImg",style:"float:left") %>
             <p style="padding: 30px 0 0 80px;font-size: 18px;">新作投稿</p>
             </div>
            <% end %>
         <% end %>
          <%= render 'novels_ichiran_format',novels:@sinsaku_nichijou_novels,genre_shurui:"日常" %>
          <%= render 'novels_ichiran_format',novels:@sinsaku_renai_novels,genre_shurui:"恋愛" %>
          <%= render 'novels_ichiran_format',novels:@sinsaku_joke_novels,genre_shurui:"ジョーク" %>
          <%= render 'novels_ichiran_format',novels:@sinsaku_siriz_novels,genre_shurui:"シリーズ" %>
          <%= render 'novels_ichiran_format',novels:@sinsaku_doutitle_novels,genre_shurui:"同タイトル" %>
         </div>


        <div class="tab-pane fade" id="profile">
          <% if user_signed_in? %>
            <%= link_to new_sss_path(past_work_flag:true) do %>
            <div style="margin:10px 10px 60px 10px;">
            <%= image_tag("pen.jpg",:size => "70x70",:class=>"hoverImg",style:"float:left") %>
            <p style="padding: 30px 0 0 80px;font-size: 18px;">過去作投稿</p></div>
           <% end %>
          <% end %>
          <div>
          <%= render 'novels_ichiran_format',novels:@past_work_nichijou_novels,genre_shurui:"日常" %>
          <%= render 'novels_ichiran_format',novels:@past_work_renai_novels,genre_shurui:"恋愛" %>
          <%= render 'novels_ichiran_format',novels:@past_work_joke_novels,genre_shurui:"ジョーク" %>
          <%= render 'novels_ichiran_format',novels:@past_work_siriz_novels,genre_shurui:"シリーズ" %>
          <%= render 'novels_ichiran_format',novels:@past_work_doutitle_novels,genre_shurui:"同タイトル" %>
          </div>
        </div>






      </div>
    </div>

    <% if !browser.device.mobile?  %>

        <button id="denkou-hyouji">電光小説　表示/非表示</button><span>・・・最新のgoogle chromeだと上手く表示されるはず<sapn>
       <div id="denkou-keiji" style="display:none">
        <p class="ledText"><span>
          <%# @novels.find_each(:batch_size => 2) do |n| %>
          <% @novels.shuffle.each do |n| %>
          作品No.<%= n.id %>
          作品名：<%= n.title %>&nbsp;&nbsp;&nbsp;
          作者名：<%= n.sakushamei %>&nbsp;&nbsp;&nbsp;
          本文：<%= n.honbun %>&nbsp;&nbsp;&nbsp;
          <% end %>
        </span></p>
      </div>

      <% end %>

  </div>

app/views/battle/_novels_nichijou0.html.erb
<% unless @nichijou_novels.empty? %>

<div class="sample-box-nichijou" >


<div class="hidari-yohaku5">
<%#= page_entries_info(@nichijou_novels) %>
&nbsp;直近５作品のみ。<%= link_to "一覧",ssses_ichiran_path(genre:"日常"),class: "btn btn-xs btn-primary"%>で全てを表示。
</div>


<table class="table table-striped table-hover hidari-yohaku5">
  <thead>
    <tr>

      <!-- <th>
       ジャンル
      </th> -->
      <th>
       新/過
      </th>
      <th>
       タイトル
      </th>

      <!-- うるまさんが居ない時にイフ追加  -->
      <% if controller.action_name != "user_about" %>
      <th>
       著者
     </th>
     <% end %>

     <th>
       投稿日時
     </th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  <% i=0 %>
    <% @nichijou_novels.each do |novel| %>
      <tr data-href="<%= sss_url(novel) %>">

        <!-- <td>
          <%= novel.genre %>
        </td> -->
        <td>
          <% if novel.past_work %>
          <span>過去</span>
          <% else %>
          <span style="font-weight:bold">新作</span>
          <% end %>

        </td>
        <td>
         <%= novel.title.truncate(20)  %>
        </td>

        <!-- うるまさんが居ない時にイフ追加  -->
        <% if controller.action_name != "user_about" %>
        <td>
          <% if @nichijou_users[i].deleted %>
          <a href="<%= ssses_user_about_url %>?user_id=<%=novel.user_id%>">退会済み</a>


          <% else %>
         <a href="<%= ssses_user_about_url %>?user_id=<%=novel.user_id%>"><%= novel.sakushamei.truncate(14)  %></a>
         <% end %>
         </td>
        <% end %>


   <% i += 1 %>

        <td>
         <%= novel.toukouhiduke.to_s(:compact_day)  %>
        </td>

        <!-- <% if  user_signed_in? && novel.user_id == current_user.id  %>
        <td class="novel btn btn-success">  <%= link_to '編集', edit_sss_path(novel) %></td>
        <td class="novel btn btn-danger">  <%= link_to '削除', sss_path(novel) , method: :delete, data: { confirm: '削除してもよろしいでしょうか?' } %></td>
        <% end %> -->
      </tr>
    <% end %>
  </tbody>
</table>
<!-- <br/> -->
<!-- 追加箇所開始 -->
<!-- <div class="center"> -->
<%#= paginate @nichijou_novels %>
<!-- </div> -->

</div>

<% end %>

app/views/battle/_show_nakami.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <% if controller.action_name == "show" %>
  <ul class ="pager">
  <li>  <%= link_to '一覧に戻る', ssses_path %></li>
        &nbsp; &nbsp; &nbsp;
  <li>  <%= link_to "←前", sss_path(@novel.previous) if @novel.previous %></li>
    &nbsp; &nbsp; &nbsp;
  <li> <%= link_to '後→', sss_path(@novel.next) if @novel.next %></li>
  </ul>
  <% end %>
  <div class="text-center opacity">



<% if browser.device.mobile? %>
<h1 style="text-align:left">

    <%= @novel.title %>

</h1>
<%else %>
  <h1>

    <%= @novel.title %>

  </h1>
<% end %>

<%= @novel.genre2_list.each do |tag| %>
<p><%= tag %></p>
<% end %>

</div>
<div class="text-left opacity">
  <li>
    <span id="txtnum"><%= mojibetu @novel.honbun %></span>
  </li>
  <li>
  <%= @novel.genre %>
</li>

<% if controller.action_name == "show" %>
<li>
<%= @novel.toukouhiduke.to_s(:compact_day)%>
</li>
<% end %>

<br/>
<li class="author">
  <% if @user.blank? %>
  著者：<a href="<%= ssses_user_about_url %>?user_id=<%=@novel.user_id%>"><%= current_user.user_about.name %></a>


  <% elsif @user.deleted == true %>
  著者：<a href="<%= ssses_user_about_url %>?user_id=<%=@novel.user_id%>">退会済み</a>
  <% elsif  @user.deleted == false %>
  著者：<a href="<%= ssses_user_about_url %>?user_id=<%=@novel.user_id%>"><%= @novel.sakushamei %></a>
  <% end %>
</li>

</div>

<div class="line space-choi novel-line"></div>

<p class="honbun" style="word-wrap:break-word; overflow: auto;">
<%= br(@novel.honbun) %>
</p>
<div style = "float:right">【投稿者：<%= @novel.sakushamei %>】</div>
<br/>
<!--　うるまさんいない時にツイート機能を追加  -->
<% if user_signed_in? && @novel.user_id == current_user.id %>
<a href="https://twitter.com/share" class="twitter-share-button" data-text="小説を書きました。" data-hashtags="超短編小説会,短編小説,小説,<%= @novel.genre %>,<%= @novel.title %>,<%= @novel.sakushamei %>">Tweet</a><span>・・・ツイッターに「書きました。」をする。</span> <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
<% else %>
<a href="https://twitter.com/share" class="twitter-share-button" data-text="小説を読みました。" data-hashtags="超短編小説会,短編小説,小説,<%= @novel.genre %>,<%= @novel.title %>,<%= @novel.sakushamei %>">Tweet</a><span>・・・ツイッターに「読みました。」をする。</span> <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
<% end %>
<br/>
<% if controller.action_name == "show" || controller.action_name == "comment_create"  %>

<% if user_signed_in? %>
  <% if @novel.user_id == current_user.id %>

  <div class="btn btn-success btn-success2">
   <% if Novel.genre_list_ssses_foram.include?(@novel.genre) %>
   <%= link_to '編集', edit_sss_path(@novel,flag:true) %>
   <% elsif Novel.genre_list_ssses_ivent.include?(@novel.genre) %>
   <%= link_to '編集', edit_sss_path(@novel,ivent_flag:true) %>
   <% else %>
   <%= link_to '編集', edit_sss_path(@novel) %>
   <% end %>
  </div>

  <div class="novel btn btn-danger">
    <%= link_to '削除', sss_path(@novel) , method: :delete, data: { confirm: '削除してもよろしいでしょうか?' } %>
  </div>

    <% end %>
    <% end %>

    <!-- <div class="btn btn-info">
    <%#= link_to '一覧に戻る', ssses_path %>
</div> -->

<ul class ="pager">
<li>  <%= link_to "←前", sss_path(@novel.previous) if @novel.previous %></li>
  &nbsp; &nbsp; &nbsp;
<li> <%= link_to '後→', sss_path(@novel.next) if @novel.next %></li>
</ul>

  <% if @comments.present? %>
  <p class="comment-ichiran"> コメント一覧　</p>
  <div class="space-choi line novel-line"></div>
  <% end %>

    <% i=1 %>
    <ol class="media-list">
      <% @comments.each do |comment| %>
      <!-- <div class="comment-kannren"> -->
      <li class="media">
        <span><%= i %>.</span>
        <% if comment.user.deleted == true %>
        <a class="media-left" href="<%= ssses_user_about_url %>?user_id=<%=comment.user_id%>"><%= image_tag("gaikotu.png",:size => "50x50") %></a>



        <div class="media-body">
        <h4 class="media-heading">
        <strong>
        <a href="<%= ssses_user_about_url %>?user_id=<%=comment.user_id%>">退会済み</a>

        <% else %>
        <a class="media-left" href="<%= ssses_user_about_url %>?user_id=<%=comment.user_id%>"><%= profile_img(comment.user.user_about) %></a>
        <div class="media-body">
          <h4 class="media-heading">
            <strong>
              <a href="<%= ssses_user_about_url %>?user_id=<%=comment.user_id%>">
                <%= comment.user.user_about.name %>
                </a>
        <% end %>
          </strong>
        </h4>
          <p style="width:100%; display:table; table-layout:fixed; font-size:18px; word-wrap:break-word; overflow-wrap : break-word;overflow: auto;"><%= br(comment.body) %></p>
        </div>
        <br />
        <!-- コメント編集未実装  -->
        <% if user_signed_in? && comment.user == current_user %>
        <span><%= link_to 'コメント編集', sss_path(comment.novel_id,comment_id:comment.id),:class=>"btn btn-xs btn-info" %></span>
        <% end %>

        <% if user_signed_in? && comment.user == current_user %>
        <span><%= link_to 'コメント削除', comment_path(comment,docchi:"sss"), method: :delete,data: { confirm: '削除してもよろしいでしょうか?' },:class=>"btn btn-xs btn-danger" %></span>
        <% end %>
      </li>
      <!-- </div> -->
      <% i +=1 %>
      <% end %>
    </ol>



    <% if user_signed_in? %>
    <%= render 'ssses/comment_form' %>
    <% end %>


  <% end %>
</div>
</div>

app/views/battle/_site_about.html.erb
<div class="container">
  <h2><strong  style="background: linear-gradient(transparent 60%, #ffff66 60%);" id="scroll_1">1. 超短編小説会について</strong></h2>
  <p>(1) 超短編小説会とは、超短編（掌編）の小説を投稿したり読んで感想を書いたりする場所です。</p>
  <p>(2) このサイトは、前身の「超短編小説会」の理念を引き継ぎ、 「作家さん同士のコミュニケーション」を主な目的としたサイトです。</p>
  <p>(3) 投稿作品は、３０００字以内を目安にお願いします。</p>
  <p>(4) 連続投稿はなるべく避けるようにしてください。他の作家さんの作品を尊重しながら活動しましょう。</p>
  </div>

app/views/battle/_user_about_form.html.erb
<!-- アクションの切り替え機能 -->
<% if controller.action_name == "new" || controller.action_name == "create"   %>
<% action = "create_user_about" %>
<% else %>
<% action = "update_user_about" %>
<% end %>

<!-- ここで、コントローラーのパラメーターとしてsssesを、アクションのパラメーターとしてcreateかアップデートを渡す  -->
<%= form_for([@user,@user_about],:url => { :controller => :ssses, :action => action }) do |f| %>

  <div class="form-group">
   <%= f.label :name,"お名前" %>
   <%= f.text_field :name %>
  </div>
  <div class="form-group">
   <%= f.label :gender,"性別" %>
   <%= f.select :gender, ["男","女"],  :prompt => "選択してください" %>
  </div>
  <div class="form-group">
   <%= f.label :birthday,"生年月日" %>
   <%= f.date_select(
        :birthday,
        start_year: 1900,
        end_year:   (Time.now.year),
        default:    Date.new(1989, 1, 1)) %>
  </div>
  <div class="form-group">
   <%= f.label :locale,"都道府県" %>
   <%= f.collection_select :locale, JpPrefecture::Prefecture.all, :code, :name %>
  </div>
  <%= f.submit "登録する" %>
<% end %>

app/views/battle/_zenran.html.erb
<table class="table table-striped table-hover hidari-yohaku5">
  
  <thead>
    <tr>
  <th>
    タイトル
  </th>

  <th>
    著者
  </th>

  <th>
    投稿日時
  </th>

  <th colspan="3"></th>
</tr>
</thead>

<tbody>
  <% novels.each do |novel| %>
    <tr data-href="<%= sss_url(novel) %>">

      <td>
       <%= novel.title.truncate(20)  %>
      </td>

      <td>
       <a href="<%= ssses_user_about_url %>?user_id=<%=novel.user_id%>"><%= novel.sakushamei.truncate(14)  %></a>
      </td>

      <td>
       <%= novel.toukouhiduke.to_s(:compact_day)  %>
      </td>

    </tr>
  <% end %>
</tbody>

</table>

app/views/battle/edit.html.erb
<!-- うるまさんが居ない時に実装4/7 -->
  <% if controller.action_name == "edit" %>
  <h1 style="text-align : left;padding:19px">【現状】</h1>
  <%= render 'ssses/show_nakami' %>
  <% end %>

<div class="container">

<%= render 'form', novel: @novel %>
</div>

<%= link_to '表示する', sss_path(@novel),:class => "btn btn-success" %>
<%= link_to '戻る', ssses_path,:class => "btn btn-warning" %>
</div>

app/views/battle/ichiran.html.erb
<% unless @sinsaku_novels.empty? && @past_work_novels.empty? %>
<div class="container">

  <div class="hidari-yohaku5" style="padding:5px;margin:10px 0 10px 0;">
    <h1><%= params[:genre] %>全覧</h1>
    <ul class="nav nav-tabs">

      <li class="active"><a href="#home" data-toggle="tab" aria-expanded="true" style="font-size:18px">新作</a></li>
      <li><a href="#profile" data-toggle="tab" aria-expanded="true" style="font-size:18px">過去作</a></li>
    </ul>



    <div id="myTabContent" class="tab-content">
      <div class="tab-pane fade active in" id="home">

      <%= render "ssses/zenran",novels:@sinsaku_novels %>

      </div>

      <div class="tab-pane fade" id="profile">

      <%= render "ssses/zenran",novels:@past_work_novels %>

      </div>
    </div>



  </div>

</div>
<% end %>

app/views/battle/index.html.erb
<% if notice %>
<div class="container">
<p id="notice1"><%= notice %></p>
</div>
<% end %>

<!-- <script type="text/javascript">
$(document).snowfall({
	flakeCount :3,			// 数
	flakeColor :'#ffffff',			// 色
	flakeIndex : 99999,			// スタイルシートのz-indexの値
	maxSpeed : 2,				// 最大速度
	minSpeed : 1,				// 最小速度
	maxSize  : 8,				// 最大サイズ
	minSize  : 5,				// 最小サイズ
});
</script> -->



<%= render "layouts/navi_short_short_story" %>

<%= render 'ssses/site_about' %>

<%= render 'ssses/koukai_shousetu' %>

<%#= render 'ssses/aisatu_shoukai' %>

<%= render "news/list" %>

<%= render 'ssses/ivent' %>

<%= render 'ssses/communication' %>

<%= render 'ssses/kaiin_list' %>




<!-- 追加箇所終了 -->


<!-- <div class="col-md-8 col-md-offset-2">
  <div class="line"></div>
</div> -->

<!-- <div class="container" style="margin-top:15px;margin-bottom:15px">
  <h1>読んだ本の感想を読む</h1>


    <%#= link_to "読んだ本の感想を読む",ssses_shousetukansous_path,class: "btn btn-warning" %>


</div> -->

<!-- <div class="col-md-8 col-md-offset-2">
  <div class="line"></div>
</div> -->

<!-- <div class="container">
  <h1>所属チーム</h1>
  <div class="bs-component">
    <ul class="nav nav-pills nav-stacked">
      <li class="active"><%= link_to "超短編小説会",ssses_path,{style:"font-size:20px" } %></li>
      <li><a href="#">サンプルチームA</a></li>
      <li><a href="#">サンプルチームB</a></li>

    </ul>
  </div>
</div> -->

app/views/battle/new.html.erb
<% if params[:flag] %>
<h1>フォーラムのトピック作成中</h1>
<%elsif params[:ivent_flag] %>
<h1>イベントのトピック作成中</h1>
<% else %>
<h1>新規小説作成中</h1>
<% end %>
<%= render 'ssses/form', novel: @novel %>

<%= link_to '戻る', ssses_path %>

app/views/battle/shousetukansous.html.erb
 <%= render 'shousetukansous/shousetukansous_list' %>

app/views/battle/show.html.erb
<%= render 'ssses/show_nakami' %>