config/routes.rb
Rails.application.routes.draw do

  get "/rooms/:user_id", :to=>"rooms#show",param: :username,as: :room

  resources :ikebanas
  resources :shousetukansous
  devise_for :admin_users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'


  resources :comments

  resources :news

  resource :votes

  root 'home#index'



  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    :registrations => 'users/registrations' }


   resources :users do
     resources :user_abouts ,:only => [:index,:create,:update,:show]
   end

  resources :novels ,:as => :novels

  get '/novels/short_short_story', to: 'novels#short_short_story', as: :short_short_story

  get '/ssses/shousetukansous', to: 'ssses#shousetukansous', as: :ssses_shousetukansous

  get '/ssses/user_about', to: 'ssses#user_about', as: :ssses_user_about

  post '/ssses/user_about', to: 'ssses#create_user_about'
  patch '/ssses/user_about', to: 'ssses#update_user_about'
  put '/ssses/user_about', to: 'ssses#update_user_about'

  # ここはsssesのコメント部

  post '/ssses/comment', to: 'ssses#comment_create'


# コメントを編集したいが、黒い画面に飛ぶ　まだ未実装
  patch '/ssses/comment', to: 'ssses#comment_update'
  put '/ssses/comment', to: 'ssses#comment_update'

  # ここはsssesのお知らせedit お試し中
  post '/ssses/news', to: 'ssses#create_news'
  patch '/ssses/news', to: 'ssses#update_news'
  put '/ssses/news', to: 'ssses#update_news'

  get '/ssses/ichiran', to: 'ssses#ichiran' ,as: :ssses_ichiran

  get '/ssses/chokkin_novels_zenran', to: 'ssses#chokkin_novels_zenran' ,as: :ssses_chokkin_novels_zenran

  # うるまさん居ない時に　4/12

  get '/ssses/show_user_about_novel', to: 'ssses#show_user_about_novel',as: :ssses_user_about_novel

  # get '/ssses/shousetukansous/:shousetukansou_id' => 'ssses#show_shousetukansou',path: "ssses/shousetukansous/:shousetukansou_id" ,as: :ssses_shousetukansou
  # get '/ssses/shousetukansous/new' => 'ssses#new_shousetukansou',path: "ssses/shousetukansous/new" ,as: :new_ssses_shousetukansou
  # get '/ssses/shousetukansous/:shousetukansou_id/edit' => 'ssses#edit_shousetukansou',path: "ssses/shousetukansous/:shousetukansou_id/edit" ,as: :edit_ssses_shousetukansou
  # post '/ssses/shousetukansous' => 'ssses#create_shousetukansou',path: "ssses/shousetukansous/" ,as: :ssses_shousetukansous
  # patch '/ssses/shousetukansous/:shousetukansou_id' => 'ssses#update_shousetukansou',path: "ssses/shousetukansou/" ,as: :ssses_shousetukansou
  # put '/ssses/shousetukansous/:shousetukansou_id' => 'ssses#update_shousetukansou',path: "ssses/shousetukansou/" ,as: :ssses_shousetukansou


# うるまさんがいない時に9/10

  get '/ssses/message_ichiran', to: 'ssses#message_ichiran', as: :ssses_message_ichiran

  resources :ssses ,:as => :ssses


  resources :shougis

  get 'about', to: 'home#about', as: :about
  get 'tukaikata', to: 'home#tukaikata',as: :tukaikata

  mount ActionCable.server => '/cable'

  get '/ssses/vote/result', to: 'votes#result' ,as: :ssses_votes_result

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @user_abouts = UserAbout.order("created_at DESC").page(params[:page])
    @users = []
    i=0
     @user_abouts.each do |user_about|
     @users[i]=User.find(user_about.user_id)
     i=i+1
     end
  end

  def about
  end

  def tukaikata
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<h1>趣味を楽しむ</h1>
<p class="sp-nakama center"><a class="btn btn-blue btn-lg space-top" href="/">戻るぼたん</a></p>

app/views/home/index.html.erb
<% if !user_signed_in?  %>

    <div class="jumbotron index">
      <div class="container">
        <h1>私の趣味、<br/>みんなの趣味</h1>
      </div>
    </div>



  <div class="container">
  <!-- line開始 -->
  <div class="col-md-8 col-md-offset-2">
    <div class="line"></div>
  </div>
  <!-- line終了 -->
  <h1><strong>"ここは何ですか？"</strong></h1>
  <div class="row">
    <div class=" col-ls-4 col-ls-offset-2 col-md-4 col-md-offset-2 col-sm-6 col-xs-12  space-top">
      <%= image_tag "about.jpg", :class=>"img-responsive", :size=> "334x222" %>
     </div>
    <div class="col-ls-4 col-md-4 col-sm-6 col-xs-12 space-top">
  <!-- <div class="description"> -->
    <ul style="font-size:18px">
    <li style="margin-bottom:10px">趣味を見つける</li>
    <li style="margin-bottom:10px">趣味仲間を見つける</li>
    <li style="margin-bottom:10px">趣味仲間と楽しむ</li>
    <li style="margin-bottom:10px">趣味を整理・研究する</li>
    <li style="margin-bottom:10px">趣味を見る・見せる</li>
    <li style="margin-bottom:10px">趣味を教える・学ぶ</li>
  </ul>
    <p style="margin-left:30px;font-size:18px;margin-bottom:10px;">など、趣味を楽しむところ</p>
  <!-- </div> -->
</div>



<div class="col-md-12 center">
      <a class="btn btn-primary btn-lg space-top space-migi" href="<%= about_url %>" role="button">詳細 &raquo;</a>
      <a class="btn btn-blue btn-lg space-top" href= "<%= tukaikata_url %>" role="button">使い方 &raquo;</a>
    </div>



</div>

<div class="col-md-8 col-md-offset-2 space-top  col-xs-12">
      <div class="line"></div>
    </div>

<% end %>




  <div class="container">
    <h1>
      <% if !user_signed_in?  %>
      <strong class="center col-xs-12 space-top">各種趣味</strong>
      <% else %>
      <strong class="center col-xs-12">各種趣味</strong>
      <% end %>
    </h1>
    <div class="row col-xs-12">

            <div class=" col-lg-3 col-md-4 col-sm-6 space-top col-xs-12">
              <div class="relative">
                <% if browser.device.mobile? %>
                <%= link_to image_tag("Natsume_Soseki_photo.jpg",:style=>"width:100%;height:auto;",:class=>"hoverImg"),novels_path %>
                <% else %>
                <%= link_to image_tag("Natsume_Soseki_photo.jpg",:size => "200x250",:class=>"hoverImg"),novels_path %>
                <% end %>
                <!-- <p class="post-title"><a style="font-weight:bold" href="/posts/72">1日一回ありがとうを言われる</a></p> -->
                <h3><%= link_to "小説",novels_path %></h3>
              </div>
            </div>

            <div class=" col-lg-3 col-md-4 col-sm-6 space-top  col-xs-12">
              <div class="relative">
                <% if browser.device.mobile? %>
                <%= link_to image_tag("masuda2.jpg",:style=>"width:100%;height:auto;",:class=>"hoverImg"),shougis_path %>
                <!-- <p class="post-title"><a style="font-weight:bold" href="/posts/72">1日一回ありがとうを言われる</a></p> -->
                <% else %>
                <%= link_to image_tag("masuda2.jpg",:size => "200x250",:class=>"hoverImg"),shougis_path %>
                <% end %>
                <h3><%= link_to "将棋",shougis_path %></h3>
              </div>
            </div>

            <div class=" col-lg-3 col-md-4 col-sm-6 space-top  col-xs-12">
              <div class="relative">
                <% if browser.device.mobile? %>
                <%= link_to image_tag("ikebana.png",:style=>"width:100%;height:auto;",:class=>"hoverImg"),:ikebanas %>
                <!-- <p class="post-title"><a style="font-weight:bold" href="/posts/72">1日一回ありがとうを言われる</a></p> -->
                <% else %>
                <%= link_to image_tag("ikebana.png",:size => "200x200",:class=>"hoverImg"),:ikebanas %>
                <% end %>

                <% if browser.device.mobile? %>
                <h3>生け花</h3>
                <% else %>
                <h3 style="margin-bottom:62px">生け花</h3>
                <% end %>
              </div>
            </div>


            <div class=" col-lg-3 col-md-4 col-sm-6 space-top  col-xs-12">
              <div class="relative">
                <% if browser.device.mobile? %>
                <%= link_to image_tag("Misuzu.jpg",:style=>"width:100%;height:auto;",:class=>"hoverImg"),"#" %>
                <!-- <p class="post-title"><a style="font-weight:bold" href="/posts/72">1日一回ありがとうを言われる</a></p> -->
                <% else %>
                  <%= link_to image_tag("Misuzu.jpg",:size => "200x250",:class=>"hoverImg"),"#" %>
                <% end %>
                <h3>詩（近日実装予定）</h3>
              </div>
            </div>



            <div class=" col-lg-3 col-md-4 col-sm-6 space-top  col-xs-12">
              <div class="relative">
                <%= link_to image_tag("koujichu.jpg",:size => "200x250"),"#" %>
                <!-- <p class="post-title"><a style="font-weight:bold" href="/posts/72">1日一回ありがとうを言われる</a></p> -->
                <h3>大衆演劇</h3>
              </div>
            </div>

            <div class=" col-lg-3 col-md-4 col-sm-6 space-top  col-xs-12">
              <div class="relative">
                <%= link_to image_tag("koujichu.jpg",:size => "200x250"),"#" %>
                <!-- <p class="post-title"><a style="font-weight:bold" href="/posts/72">1日一回ありがとうを言われる</a></p> -->
                <h3>カラオケ</h3>
              </div>
            </div>

<!-- <div class=“row”>
          <div class="col-md-12　col-xs-12 center">
            <p><a class="btn btn-blue btn-lg space-top" href="/new_topic">他のジャンルを見る</a></p>
          </div>
</div> -->

</div>
</div>

<div class="col-md-8 col-md-offset-2 space-top">
  <div class="line"></div>
</div><br />

<div class="container">
 <div class="col-md-8 col-md-offset-2 col-xs-12">
<h1> <strong class="center">会員様</strong>　</h1>
      <% i=0 %>
        <% @user_abouts.each do |user_about| %>
              <% if !@users[i].deleted %>
              <a href= "<%= user_user_about_url(user_id: user_about.user_id, id: user_about.id) %>"><%= user_about.name.truncate(14)  %></a>
             <span>  </span>
             <% end %>
       <% i += 1 %>
       <% end %>
 <div class="line" style="margin-bottom:10px"></div>
</div>
</div>


<% if !user_signed_in?  %>


    <div class="row">
    <div class="space-top"></div>
     <div class="col-ls-3 col-ls-offset-3 col-md-3 col-md-offset-3 col-sm-3 col-sm-offset-3 col-xs-10 col-xs-offset-1">
    <%= link_to image_tag("maneki.png",:size => "180x180",:class =>"img-responsive"),"#" %>
      <!-- <img alt="ship" class="img-responsive" src="/assets/ship_blue-dd74bcc41d9d66572a8a5084cfcce8f6722819f3f4dfd81da8edd75bd3f146ce.png" height="250" width="250"> -->
    </div>
    <div class="col-ls-6 col-md-6 col-sm-6 col-xs-12">
      <h1 class="blue start-travel sp-nakama"><strong>入会しますか？</strong></h1>
        <div class="description blue sp-nakama">
          <p>趣味を一緒にやろう</p>
          <p>一人ではできないことも出来るぞ。</p>
        </div>
        <div class="space-top">
          <p class="sp-nakama"><a class="btn btn-blue btn-lg space-top" href="<%= user_facebook_omniauth_authorize_url %>">サイトに登録</a></p>
        </div>
    </div>

  <% end %>


      <!-- line開始 -->
      <!-- <div class="col-md-8 col-md-offset-2 space-top">
        <div class="line"></div>
      </div> -->
      <!-- line終了 -->
    </div>
  </div>

app/views/home/tukaikata.html.erb
<h1>ボタンを押したり、入力する</h1>
<p class="sp-nakama center"><a class="btn btn-blue btn-lg space-top" href="/">戻るぼたん</a></p>