config/routes.rb
Rails.application.routes.draw do

  get "/rooms/:user_id", :to=>"rooms#show",param: :username,as: :room

  resources :ikebanas
  resources :shousetukansous
  devise_for :admin_users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'


  resources :comments

  resources :news

  resource :votes

  root 'home#index'



  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    :registrations => 'users/registrations' }


   resources :users do
     resources :user_abouts ,:only => [:index,:create,:update,:show]
   end

  resources :novels ,:as => :novels

  get '/novels/short_short_story', to: 'novels#short_short_story', as: :short_short_story

  get '/ssses/shousetukansous', to: 'ssses#shousetukansous', as: :ssses_shousetukansous

  get '/ssses/user_about', to: 'ssses#user_about', as: :ssses_user_about

  post '/ssses/user_about', to: 'ssses#create_user_about'
  patch '/ssses/user_about', to: 'ssses#update_user_about'
  put '/ssses/user_about', to: 'ssses#update_user_about'

  # ここはsssesのコメント部

  post '/ssses/comment', to: 'ssses#comment_create'


# コメントを編集したいが、黒い画面に飛ぶ　まだ未実装
  patch '/ssses/comment', to: 'ssses#comment_update'
  put '/ssses/comment', to: 'ssses#comment_update'

  # ここはsssesのお知らせedit お試し中
  post '/ssses/news', to: 'ssses#create_news'
  patch '/ssses/news', to: 'ssses#update_news'
  put '/ssses/news', to: 'ssses#update_news'

  get '/ssses/ichiran', to: 'ssses#ichiran' ,as: :ssses_ichiran

  get '/ssses/chokkin_novels_zenran', to: 'ssses#chokkin_novels_zenran' ,as: :ssses_chokkin_novels_zenran

  # うるまさん居ない時に　4/12

  get '/ssses/show_user_about_novel', to: 'ssses#show_user_about_novel',as: :ssses_user_about_novel

  # get '/ssses/shousetukansous/:shousetukansou_id' => 'ssses#show_shousetukansou',path: "ssses/shousetukansous/:shousetukansou_id" ,as: :ssses_shousetukansou
  # get '/ssses/shousetukansous/new' => 'ssses#new_shousetukansou',path: "ssses/shousetukansous/new" ,as: :new_ssses_shousetukansou
  # get '/ssses/shousetukansous/:shousetukansou_id/edit' => 'ssses#edit_shousetukansou',path: "ssses/shousetukansous/:shousetukansou_id/edit" ,as: :edit_ssses_shousetukansou
  # post '/ssses/shousetukansous' => 'ssses#create_shousetukansou',path: "ssses/shousetukansous/" ,as: :ssses_shousetukansous
  # patch '/ssses/shousetukansous/:shousetukansou_id' => 'ssses#update_shousetukansou',path: "ssses/shousetukansou/" ,as: :ssses_shousetukansou
  # put '/ssses/shousetukansous/:shousetukansou_id' => 'ssses#update_shousetukansou',path: "ssses/shousetukansou/" ,as: :ssses_shousetukansou


# うるまさんがいない時に9/10

  get '/ssses/message_ichiran', to: 'ssses#message_ichiran', as: :ssses_message_ichiran

  resources :ssses ,:as => :ssses


  resources :shougis

  get 'about', to: 'home#about', as: :about
  get 'tukaikata', to: 'home#tukaikata',as: :tukaikata

  mount ActionCable.server => '/cable'

  get '/ssses/vote/result', to: 'votes#result' ,as: :ssses_votes_result

end

app/models/news.rb
class News < ApplicationRecord
  enum category: { zentai: 0, novel: 10, ssses: 11, ikebana: 20 }

  scope :new_news, -> { where("expired_at >= ?",DateTime.now).or(News.where(expired_at:nil)) }
  scope :old_news, -> { where("expired_at < ?",DateTime.now) }
  scope :order_d, -> { order(created_at: :DESC) }
  scope :ikebana, -> { where(category: ['ikebana', 'zentai']) }
  scope :ssses, -> { where(category: ['ssses', 'zentai']) }

end

app/controllers/news_controller.rb
class NewsController < ApplicationController


  before_action :authenticate_admin_user! , only:[:new,:create,:edit,:update,:destroy]
  before_action :set_new, only: [:show, :edit, :update, :destroy]

  layout :layout_select

  def layout_select
    case params[:from]
    when "ssses"
      'short_short_story'
    end
  end



  def index
    @news = News.all
  end

  def show
  end

  def new
    @new = News.new
  end

  def create
    @new = News.new(news_params)

    respond_to do |format|
      if @new.save
        format.html { redirect_to ssses_path, notice: 'お知らせ出来ました' }
        format.json { render :show, status: :created, location: @new }
      else
        format.html { render :new }
        format.json { render json: @new.errors, status: :unprocessable_entity }
      end
    end

  end

  def edit
  end

  def update
    respond_to do |format|
      if @new.update(news_params)
          format.html { redirect_to ssses_path, notice: 'お知らせ編集完了' }
          format.json { render :show, status: :created, location: @new }
      else
        format.html { render :edit }
        format.json { render json: @new.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @new.destroy
    respond_to do |format|
      format.html { redirect_to ssses_url, notice: 'お知らせ消した' }
      format.json { head :no_content }
    end
  end

  private

    def set_new
      @new = News.find(params[:id])
    end

    def news_params
      params.require(:news).permit(:title,:body,:expired_at,:category)
    end

end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/news/_edit_form.html.erb
<h1>お知らせの編集中</h1>


<%= render 'form', new: @new %>


<%= link_to '表示する', @new %>
<%= link_to '戻る', news_path %>

app/views/news/_form.html.erb
<div class="container">


  
<%= form_for(@new) do |f| %>
  <% if @new.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@new.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @new.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
  <%= f.label :title,"タイトル"%><br/>
  <% if browser.device.mobile? %>
  <%= f.text_field :title %>
  <% else %>
  <%= f.text_field :title,style: "width:100%" %>
  <% end %>
  </div>

  <div class="form-group">
  <%= f.label :body,"お知らせ内容"%><br/>
  <% if browser.device.mobile? %>
  <%= f.text_area :body ,:style =>"width:100%;height:400px",:id=>"count" %>
  <% else %>
  <%= f.text_area :body,:style =>"width:100%;height:700px",:id=>"count" %>
  <% end %>
  </div>

  <div class="form-group">
  <%= f.label :expired_at,"掲載期限"%><br/>
  <%= f.datetime_select(
    :expired_at,
    end_year:          (Time.now.year + 100),
    )  %>


  </div>

  <% if params[:category] == "ssses" %>
  <%= f.hidden_field :category, :value => params[:category] %>
  <% end %>

  <div class="actions">
    <%= f.submit "お知らせ発信" %>
  </div>
<% end %>

</div>

app/views/news/_ivent_nakami.html.erb
<% ivents.each do |f| %>
<dt><%= f.created_at.strftime('%Y/%m/%d')  %></dt>
<dd style="margin-bottom:10px;">
  <%= link_to f.title,news_detail_path(f) %>
  &nbsp;

</dd>
<% end %>

app/views/news/_list.html.erb
<div class="container" >
  <div class="update" style="font-size:18px">
    <h2><strong id="scroll_3">1. お知らせ</strong></h2>
<h3><strong id="scroll_3">
</br>
平素は超短編小説会をご利用いただきありがとうございます。</br></br>
さて、以前は無料で本サイトを運用できていましたが、ちょうど１年前ぐらいから月１０＄かかるようになりました。
この有料は、HEROKUと言うサービスを運用していた大会社Salesforceの方針転換によるものです。
世知辛い世の中になりましたが、会社は利益を産むためのもの。
よくよく考えると、今まで無料で出来ていたのがある摩訶不思議であり、今回、有料に切り替わったことは当然の成り行きとも思えます。
で、私としては月１０＄の有料は正直痛いが、「本サイトはみんなの遊び場所。守りたい！」、と言う思いから、１年ばかし月１０＄を支払い続けてきました。
ちょっと設定料金が高いが、ソコはみんなのために・・・・（くどいし、恩着せがましい笑）</br></br>
さあーさあー、話は続きますよ。</br></br>
そんな中、ある日、どんぶらこー・どんぶらこー、とイーロン○スクなるケッタイなオッチャンが「X」の紋章の黒船に乗ってやってきました。
２０２３年６月頃でしたか、その身勝手なオッちゃんの独裁的な行いにより、突然、本サイトに再ログイン出来なくなりました。
もっとも次のように月１００＄ほど払って出来そうだけど、</strong></h3>
<%= image_tag("mask.png",class: "img-responsive",width: "90%") %>
<h3><strong id="scroll_3"></br>
そのとおり！実は本サイトはツイッターを利用した認証システムでログインする仕組みだったのです。
まあ、そう言ったことで、HEROKUの月１０＄の支払いなら何とか持ち堪えていたが、オッチャンの会社「twitter」ならぬ「X」のためにさらに＋月１００＄も追加で払うことになると話は別です。</br></br>
「おいおい、勘弁してくれよー！　いくらなんでも毎月１１０＄も払えるかよ！！」である。😡</br></br>
長らくご愛顧いただいていた本サイトもいよいよ、閉幕することになりました。断腸の思いであります。</br></br>
それではみんな、達者でな！風邪引くなよー！　（＞＜）／サラバ　</br></br></br>
敬具 ２０２３　KENIO
</br>
</br>
</br>
</br>
</br>
おっとと　忘れていました。いけないいけない・・・・
</br>実は、本サイトリニューアルすることになりました。😁「はよ言えや！」って話であるが、もったいつけてみました。😁
</br></br>こちらが新しいサイトのリンク先です。</strong></h3>
<a href="http://choutanpen-shumi.com/wordpress/" target="_blank">ここをクリックすると飛びます。</a>
<h3><strong id="scroll_3"></br>
</br>新サイトはワードプレスってサイトの機能で作りました。今回は、なかまくらさんが主にサイトを作りました。（けにおも、多少は手伝った！）
</br>
</br>あとなあ、本サイト（ワードプレスの新サイトやのうて、今いるHEROKUのサイトの方な）は本当に店仕舞いにするんで、もし必要なら、今のウチに自分の小説をコピペするなり保存しときやー
</br>あとになって、「無くなった。復活させろー！俺の小説返せー！」とか言われても、もう出来ひんでー！泣こうが喚こうが、もう知らんでー！
</br>本サイト（ワードプレスの新サイトやのうて、今いるHEROKUのサイトの方な）は２０２４年２月いっぱいや思うとってやー！
</br>それまでに自分の作った小説をコピペして、どっか例えばワードなんかに保存しとくんやでー！
</br>ここ大事なんで、もっかい言うとく！もし自分が作った小説を残したいなら、２０２４年２月までに自分の小説をコピペして自分のパソコン内なんかに保存すんねんでー！ええな！😎

</br></br>では、再会✋
</br></br>
</strong></h3>

    <% if current_admin_user %>
    <div><%= link_to "お知らせの作成",new_news_path(from:@params,category: "ssses"),:class => "btn btn-success" %></div>
    <% end %>

    <div class="hidari-yohaku5" style="padding:5px;margin:10px 0 10px 0;">
      <ul class="nav nav-tabs">
        <li class="active"><a href="#now_news" data-toggle="tab" aria-expanded="true" style="font-size:18px">現在NEWS</a></li>
        <li><a href="#old_news" data-toggle="tab" aria-expanded="true" style="font-size:18px">過去NEWS</a></li>
        <li><a href="#ivent" data-toggle="tab" aria-expanded="true" style="font-size:18px">イヴェント</a></li>

      </ul>

      <div id="myTabContent" class="tab-content">

        <div class="tab-pane fade active in" id="now_news">
          <%= render 'news/news_nakami',news:@now_news %>
        </div>
        <div class="tab-pane fade" id="old_news">
          <%= render 'news/news_nakami',news:@old_news %>
        </div>

        <div class="tab-pane fade" id="ivent">
          <%= render 'news/ivent_nakami',ivents:@ivents %>
        </div>

      </div>
    </div>

  </div>

</div>

app/views/news/_news_nakami.html.erb
<% news.each do |f| %>
<dt><%= f.created_at.strftime('%Y/%m/%d')  %></dt>
<dd style="margin-bottom:10px;"><a href="javascript:void(0);" data-toggle="popover" data-html="true" data-placement="bottom" data-content= "<%= f.body %>" ><%= f.title %></a>
  &nbsp;
  <% if current_admin_user %>
  <%= link_to '編集', edit_news_path(f),class:"btn btn-info" %>
  <%= link_to '削除', news_path(f) , method: :delete, data: { confirm: '削除してもよろしいでしょうか?' },class:"btn btn-danger" %>
  <% end %>
</dd>
<% end %>

app/views/news/_show_form.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<p>
  <strong>タイトル:</strong>
  <%= @new.title %>
</p>

<p>
  <strong>ニュース内容:</strong>
  <%= @new.body %>
</p>

<% if current_admin_user %>
<%= link_to '編集', edit_news_path(@new) %> |
<%= link_to '戻る', ssses_path %>
<% end %>

</div>

app/views/news/edit.html.erb
<%= render 'news/edit_form' %>

app/views/news/index.html.erb
  <%= render "news/list" %>

app/views/news/new.html.erb
<h1>お知らせ作成中</h1>

<%= render 'form', new: @new %>

<%= link_to '戻る', news_index_path %>

app/views/news/show.html.erb
<%= render "news/show_form" %>